### ISSUE TITLE
Create CSV instead of SSV

### ISSUE THREAD

**Issue by snaeqe** [berlinonline/haeufige-vornamen-berlin#1]
>  We can make this file beautiful and searchable if this error is corrected: No commas found in this CSV file 

Using commas instead of semicolon will not worsen machine-readability but improve the ability to play with the data using github features.
So please consider changing the output separator from ; to ,

Thanks :)

**Comment by knudmoeller** [comment]
Yes, you're right! We chose to leave the semicolon because that's how the original version of the data is formatted. But, seeing as we are already changing the order of the columns and filtering out noise, we might just as well change the separator as well. I'll do it in a separate branch first, and merge that in to `master` in the near future.

**Comment by knudmoeller** [comment]
There you go, true CSVs: https://github.com/berlinonline/haeufige-vornamen-berlin/tree/feature/comma-separator

**Comment by knudmoeller** [comment]
Ok, `master` now has true CSVs; I'm closing the issue.
